theme: jekyll-theme-minimal
title: BDA-503 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Group Division Bell's Journal
description: Welcome to our journal, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this is **<a href="https://pjournal.github.io/mef05-liophire/">Emirhan Şahin</a>**, **<a href="https://pjournal.github.io/mef05-mctasar/">Murat Can Taşar</a>**, **[Nejat Uğur Akın](https://pjournal.github.io/mef05-nejatugurakin/)**, **[Yunus Emre Doğan](https://pjournal.github.io/mef05-yunusemre91/)**.

# theme: jekyll-theme-cayman
# title: Division Bell
# description: BDA503 Fall 2021 - MEF University
