theme: jekyll-theme-minimal
title: BDA-503 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Group Division Bell's Journal
description: Welcome to our journal, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this is <a href="https://github.com/pjournal/mef05-liophire">Emirhan Şahin</a>, <a href="https://github.com/pjournal/mef05-mctasar">Murat Can Taşar</a>, <a href="https://github.com/pjournal/mef05-nejatugurakin/">Nejat Uğur Akın</a>(), <a href="https://github.com/pjournal/mef05-yunusemre91">Yunus Emre Doğan</a>. The link above will take you to individual GitHub pages.

# theme: jekyll-theme-cayman
# title: Division Bell
# description: BDA503 Fall 2021 - MEF University
