theme: jekyll-theme-minimal
title: BDA-503 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Group Divion Bell's Journal
description: Welcome to our journal, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this is **[Emirhan Şahin](https://pjournal.github.io/mef05-liophire/)**
* **[Murat Can Taşar](https://pjournal.github.io/mef05-mctasar/)**
* **[Nejat Uğur Akın](https://pjournal.github.io/mef05-nejatugurakin/)**
* **[Yunus Emre Doğan](https://pjournal.github.io/mef05-yunusemre91/)**.

# theme: jekyll-theme-cayman
# title: Division Bell
# description: BDA503 Fall 2021 - MEF University
